# Compositor: elimina tearing-ul pe Intel UHD 730
backend = "glx";
vsync = true;
use-damage = true;

shadow = false;
fading = true;
fade-delta = 4;

corner-radius = 0;

opacity-rule = [
  "95:class_g = 'Alacritty' && focused",
  "88:class_g = 'Alacritty' && !focused"
];
